### ISSUE TITLE
CSWSH ORIGIN BYPASS DETECTED ?

### ISSUE THREAD

**Issue by Sim4n6** [PalindromeLabs/STEWS#1]
Hi,

In case, I get 

> >>>CSWSH ORIGIN BYPASS DETECTED: wss://REDACTED.com/ws vanilla CSWSH didn't work, but server origin check was bypassed (unescaped period). 

Does that mean CSWSH is still possible ?? if so, how to set the Origin header to REDACTEDAcom ? 

Thank you in davance

**Comment by engn33r** [comment]
You get this message when any of result102, result103, result104, result105, or result106 is true
https://github.com/PalindromeLabs/STEWS/blob/main/vuln-detect/STEWS-vuln-detect.py#L185

The script doesn't indicate which of these cases triggered the message, so you can modify the code to indicate which if these tests was true. Or you can try the five different cases manually:
https://github.com/PalindromeLabs/STEWS/blob/main/vuln-detect/STEWS-vuln-detect.py#L157-L167

**Comment by Sim4n6** [comment]
Thank you for the clarification
