### ISSUE TITLE
FATA[0000] cipher suites: unable to convert portable to a 16bit integer: strconv.ParseUint: parsing "portable": invalid syntax 

### ISSUE THREAD

**Issue by anoduck** [PalindromeLabs/STEWS#2]
1. Built zgrab2 fork maintained by PalindromeLabs and added to `$PATH`
2. Created alias for `shuf` to `gshuf`. Particular to my system.
3. Then Later, modified the script to use `gshuf` rather than `shuf`, due to still receiving complaints.
4. Resulted in error `FATA[0000] cipher suites: unable to convert portable to a 16bit integer: strconv.ParseUint: parsing "portable": invalid syntax` when ran with provided `known-endpoints.txt` file.

Point of information: Assuming `shuf` refers to the program that is a part of GNU coreutils. My system (OpenBSD) does not include a `shuf` command, only `gshuf` is provided via the installation of GNU coreutils.

**Comment by engn33r** [comment]
I did not encounter any errors like this so I cannot suggest any solutions

**Comment by anoduck** [comment]
> I did not encounter any errors like this so I cannot suggest any solutions

Interesting, because I was able to reproduce the same error on a different machine running Kali (Debian) Linux. So, it is reproducible, and not OS specific. 

Since the error obviously relates to the forked version of zgrab2. 

1. How are you building zgrab2?
2. Except for simply cloning and executing `make`, are there any "feature" flags?
3. Could this possibly be a library versioning issue?

**Comment by engn33r** [comment]
I would suggest that you first confirm that you can build the original zgrab2 repository instead of the forked repository. The modifications made in the forked version are extremely minor and do not impact the build process.

**Comment by anoduck** [comment]
Of course, I can build the original. If the modifications are minor, do not affect the build process, and I can build the forked version. Then obviously, logic tells us, I can build the original as well.

Just to prove the apparent, I checked, and big surprise… I can build the original.

-----

To be honest, the need for the project is now moot. I was just doing the responsible thing, by reporting bugs and issues to the developer. 

I will let you get back to whatever else you were doing.
